### ISSUE TITLE
Last Session

### ISSUE THREAD

**Issue by nimaafallah** [pouyaSamie/FreeInternet#1]
سلام دوست عزیز ممنون از اموزشت
قسمت اخر که Config Nginx for your V2ray هست
وقتی اضافه میکنیم و ریست میکنیم nginx رو تست میگیرم اررور میده!
ممکنه یه کانفیگ  از قسمت اخر بزارید؟

**Comment by pouyaSamie** [comment]
full nginx config `/etc/nginx/nginx.conf`:
```console

user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

# Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 4096;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    include /etc/nginx/conf.d/*.conf;

    include /etc/nginx/sites-enabled/*.conf;
    server_names_hash_bucket_size 64;
}
```

One web site config in `/etc/nginx/sites-enabled/sample.com.conf` :

```console
server {
        root /var/www/sample.com/public_html;

        server_name sample.com www.sample.com;

   # Random path from ws in v2ray
   location /y2uaetfp83b {
        proxy_redirect off;
        proxy_pass http://127.0.0.1:59689; #v2ray port
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;

    }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/www.sample.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/www.sample.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = sample.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = www.sample.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        listen 80;
        listen [::]:80;
        server_name sample.com www.sample.com;
    return 404; # managed by Certbot
}
```

**Comment by MDavDav** [comment]
> سلام دوست عزیز ممنون از اموزشت قسمت اخر که Config Nginx for your V2ray هست وقتی اضافه میکنیم و ریست میکنیم nginx رو تست میگیرم اررور میده! ممکنه یه کانفیگ از قسمت اخر بزارید؟

منم مشکل مشابه دارم

**Comment by pouyaSamie** [comment]
یا خطاتون رو بفرستید یا کانفگ هاتون رو تا جایی که بتونم راهنمایی میکنم 😊

**Comment by nimaafallah** [comment]
> یا خطاتون رو بفرستید یا کانفگ هاتون رو تا جایی که بتونم راهنمایی میکنم 😊

root@vp22.g:~# sudo vim /etc/nginx/nginx.conf
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 768;
        # multi_accept on;
}


        location /NimaNima {
                proxy_redirect off;
                proxy_pass http://0.0.0.0:2083;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $http_host;

        }
http {

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        types_hash_max_size 2048;
        # server_tokens off;

        server_names_hash_bucket_size 64;
        # server_name_in_redirect off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ##
        # SSL Settings
        ##

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;

        ##
        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        ##
        # Gzip Settings
        ##

        gzip on;

        # gzip_vary on;
        # gzip_proxied any;
        # gzip_comp_level 6;
        # gzip_buffers 16 8k;
        # gzip_http_version 1.1;

**Comment by nimaafallah** [comment]
مهندس من آی دی تلگرام بزارم امکانش هست پیام بدین؟ یا ایمیل

**Comment by pouyaSamie** [comment]
ایمیل بزارید من امشب بررسی میکنم براتون

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nimaafallah** [comment]
nimafallah@outlook.com

خیلی محبت میکنید ، ممنون ازتون

**Comment by pouyaSamie** [comment]
سلام این کانفیگ اشتباه هست من مجدد بخش ساخت وب سایت رو آپدیت میکنم توضیحاتم رو واضح تر میکنم باز مشکلی بود بگین بهم.

ولی مشکل اصلی اینه که اصلا دامنه توی فایل تعریف نشده

**Comment by nimaafallah** [comment]
سلام مجددپویا جون
اگه یه ایمیل بمن بدین من اکانتمو میدم بهتون اگه زحمتی نسیت چک کنید، من همه مراحل رو مثل اموزشتون پیش رفتم :(

**Comment by nimaafallah** [comment]
من این فایل رو ادیت نکردم One web site config in /etc/nginx/sites-enabled/sample.com.conf :

اینجا رو طبق امورشتون ادیت میکنم و اضافه میکنم location رو:
sudo vim /etc/nginx/nginx.conf

**Comment by nimaafallah** [comment]
Pouya Jan Maro Faramosh Nakoni :')

**Comment by pouyaSamie** [comment]
سلام ببخشید من این چند روز درگیر بودم 
قسمت کانفیگ Nginx رو عوض کردم کلا
https://github.com/pouyaSamie/FreeInternet#Website
ساده ترش کردم که کمتر پیچیدگی داشته باشه. اگر بارم مشکل داشتید بهم بگین

**Comment by nimaafallah** [comment]
تشکر فراوان ممنون از وقتی که گذاشتین
فقط یه سوال اینکه حتما باید از خود xui اس اس ال بگیریم؟
بصورت manual نمیشه؟

**Comment by nimaafallah** [comment]
nginx: [emerg] getpwnam("nginx") failed in /etc/nginx/nginx.conf:1
nginx: configuration file /etc/nginx/nginx.conf test failed


بازم نشد :(

**Comment by pouyaSamie** [comment]
> nginx: [emerg] getpwnam("nginx") failed in /etc/nginx/nginx.conf:1 nginx: configuration file /etc/nginx/nginx.conf test failed
> 
> بازم نشد :(
کامل nginx.conf رو بزار اگه بتونی زیپ کنی بفرستی که بهتره

**Comment by nimaafallah** [comment]
[nginx.zip](https://github.com/pouyaSamie/FreeInternet/files/10783845/nginx.zip)

**Comment by nimaafallah** [comment]
> > nginx: [emerg] getpwnam("nginx") failed in /etc/nginx/nginx.conf:1 nginx: configuration file /etc/nginx/nginx.conf test failed
> > بازم نشد :(
> > کامل nginx.conf رو بزار اگه بتونی زیپ کنی بفرستی که بهتره

ostad feretsdam havasam nabod replay nakardam

**Comment by pouyaSamie** [comment]
> > > nginx: [emerg] getpwnam("nginx") failed in /etc/nginx/nginx.conf:1 nginx: configuration file /etc/nginx/nginx.conf test failed
> > > بازم نشد :(
> > > کامل nginx.conf رو بزار اگه بتونی زیپ کنی بفرستی که بهتره
> 
> ostad feretsdam havasam nabod replay nakardam

سلام من فایل رو بررسی کردم دو تا مشکل داشت اولیش این بود که توی Ubunto یوزر www-data یوزری هست که باید استفاده بشه (خط اول فایل) و انتهای فایل هم یک آکولاد بسته کم داشت من تغییرات رو دادم براتون فایل رو میزارم.
[nginx.zip](https://github.com/pouyaSamie/FreeInternet/files/10801162/nginx.zip)

**Comment by nimaafallah** [comment]
dastet dard nakoneeeee agha, ok shod , kheyli kheyli mamnoon
